language: php

php:
  - '7.1'
  - '7.2'

services:
  - mysql

env:
  global:
    - CC_TEST_REPORTER_ID=5acc45b5f48d4ca2a5baa0d22ee9a10890b29a76b3ef34a936fdd0ba8c5d7ba8
    - DB_HOSTNAME=127.0.0.1
    - DB_DATABASE=slim
    - DB_USERNAME=root
    - DB_PASSWORD=

before_install:
  - mysql -e 'CREATE DATABASE slim;'

before_script:
  - mysql slim < bd/slim.sql
  - composer install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter 
  - chmod +x ./cc-test-reporter 
  - ./cc-test-reporter before-build

install:
  - travis_retry composer update --prefer-dist --prefer-stable

script:
  - ls $TRAVIS_BUILD_DIR
  - ls $TRAVIS_BUILD_DIR/Tests
  - ls $TRAVIS_BUILD_DIR/vendor/bin/phpunit
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit $TRAVIS_BUILD_DIR/Tests/EnvparserTest.php --coverage-clover=coverage.xml
