language: php


php:
  - '7.1'

sudo: required

services:
  - docker
  - mysql

env:
  global:
    - CC_TEST_REPORTER_ID=5acc45b5f48d4ca2a5baa0d22ee9a10890b29a76b3ef34a936fdd0ba8c5d7ba8
    - DB_HOSTNAME=127.0.0.1
    - DB_DATABASE=slim
    - DB_USERNAME=root
    - DB_PASSWORD=

before_install:
  - mysql -e 'CREATE DATABASE slim;'

before_script:
  - mysql slim < bd/slim.sql
  - composer install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter 
  - chmod +x ./cc-test-reporter 
  - ./cc-test-reporter before-build

script:
  - vendor/bin/phpunit --coverage-text
  - sudo apt-get -y install libxml2 libxml2-dev
  - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - export REPO=bhavikk/level-three-rest
  - docker build -t $REPO:$TAG -f Dockerfile 

 after_success:
 - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
 - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
   docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER;
   docker push $REPO:$TRAVIS_BUILD_NUMBER;
   fi 
 - docker push $REPO:$TAG
